### ISSUE TITLE
Handle Multiple Images

### ISSUE THREAD

**Issue by eggers** [Vibrant-Colors/node-vibrant#60]
Any potential of enhancing the library to take a list of images? I have some video thumbs, and it would be interesting to get the primary colors that are in all of them images.

I could do it with more work by adding the images to a canvas and then transferring that to an img tag. Or creating a stitched image, but it'd be nice if the library could handle it.

**Comment by gmemstr** [comment]
Wouldn't it be easier to just do a `for` loop, and store it all in an object?

**Comment by akfish** [comment]
In the next version I'll expose the process pipeline API. It should be flexible to do what you want with some custom code.

**Comment by mike-battistella** [comment]
Is this feature underway?
Is there another possibility to get the palettes for multiple images? In the fullfillment function of the promise I have no way to know for which image the palette is returned. I cannot be sure if the order of the calls is kept because some image could load slower and some quicker. So the callback functions could be called in another order (or do I understand something wrong)?
It would be helpful if the palette object which is returned would contain the original URL or some other indicator to identify the image.

**Comment by sandstrom** [comment]
@mike-battistella That should be trivial to handle in your own code, I don't think this "feature" is something the library itself should be concerned with.

**Comment by sandstrom** [comment]
Since this is pretty old and should be possible to solve in the application code, maybe this could be closed? (or moved to discussions, though you'd have to enable that for this repo first).

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by crutchcorn** [comment]
Closing in favor of a `for` loop currently, with a processor pipeline in the rewrite down the road
