### ISSUE TITLE
Is there any way to select a region of an image to sample?

### ISSUE THREAD

**Issue by AlexThomas90210** [Vibrant-Colors/node-vibrant#70]
I would like to specify the region in pixels to sample in eg (x, y, width, height) of a square, then I would the dominant color for that region?

**Comment by maxcr** [comment]
Mark this as a feature request.

**Comment by 1j01** [comment]
In Node.js, you could use one of these:
- https://www.npmjs.com/package/jimp
- https://www.npmjs.com/package/gm
- https://www.npmjs.com/search?q=imagemagick
- https://www.npmjs.com/package/sharp

In the browser you could use canvas (with `drawImage`), altho it looks like you'd have to use `toDataURL` or `toBlob` until `<canvas>`-as-a-source support is added, see https://github.com/akfish/node-vibrant/issues/75

**Comment by crutchcorn** [comment]
One solution for this would be to crop the image first using a library like those mentioned by @1j01. However, we don't want to prevent asking for info. Marking as feature request, we'll come back to this after finishing work on bugs and documenting and cleaning up the monorepo work we've done

**Comment by sandstrom** [comment]
Since this can easily be solved in application code (as explained above), maybe it could be closed? (or moved to discussions, though you'd have to enable that for this repo first).

By closing some old issues we reduce the list of open issues to a more manageable set.

Many open-source projects expand their scope too much, and become difficult to maintain. It's usually better to keep the scope smaller, making it easier to maintain.

**Comment by crutchcorn** [comment]
Marking this as closed, since it should be done ahead-of-time in another package as mentioned previously
